### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by nomorehey** [immunIT/drupwn#40]
Traceback (most recent call last):
  File "drupwn", line 48, in <module>
    Fingerprinter(request, logger).fingerprint(config)
  File "/home/dwpt/drupwn/engine/Fingerprinter.py", line 25, in fingerprint
    config["version"] = float(version.group(0))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by wh1t3p4wn48** [comment]
Hi @nomorehey 
This issue, releated to newer versions of Drupal 8, is now fixed.
